# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://localhost/db_muebleria?allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=debug


# ===============================
# JWT
# ===============================

jwt.secret=YOUR_JWT_SECRET
jwt.expiration=${JWT_EXPIRATION:86400000}


# ===============================
# FILE STORAGE
# ===============================

app.storage.catalogo=YOUR_LOCAL_STORAGE_PATH_CATALOGO




spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# PDF EMPRESA
# ===============================

empresa.nombre=${EMPRESA_NOMBRE:Mueblerías}
empresa.rfc=${EMPRESA_RFC:RFC_DEMO}
empresa.correo=${EMPRESA_CORREO:ventas@empresa-demo.com}
empresa.telefono1=${EMPRESA_TELEFONO1:0000000000}